version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    ports:
      - "9000:9000"
      - "9004:9004"  # Port for Xdebug
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - symfony

  web:
    image: nginx:latest
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    networks:
      - symfony

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  database_data:
